export const factList = () => {
	return [
		{ id: '1', title: 'Internet storage holds at least 1,200 petabytes worth of data.', body: 'This estimate is equivalent to 1.2 billion terabytes. This number is only an estimation between the big 4 - Google, Facebook, Microsoft, and Amazon.<br>This figure is also still exclusive of other bigtime providers such as Dropbox, SugarSync, and Barracuda.' },
		{ id: '2', title: 'Each day, about 4,000 ransomware attacks are executed.', body: 'The average amount that perpetrators demand after an attack is $1,077.' },
		{ id: '3', title: 'Currently, there are approximately 4.9 billion internet users', body: 'According to Statista Research Department, the global number of internet users in 2021 was 4.9 billion, up from 4.6 billion in 2020.' },
		{ id: '4', title: 'NASA has an internet speed of 91 gigabits per second.', body: 'It is 13,000 times faster than the internet speed of the average user in the United States.' },
		{ id: '5', title: 'The company that invented the modem was a successor of Alexander Graham Bell', body: 'In 1958, Bell Labs invented the very first modem. The company was the descendent of telephone inventor Alexander Graham Bell, and the modem capitalized on phone lines as a great way to “beep” information back and forth—like the telltale dial-up modem sound many of us could probably still hum today.' },
		{ id: '6', title: 'The first network of four computers were linked in 1969', body: 'Today, most of the world is interlinked with a massive cabling infrastructure that includes gigantic cables beneath all the world’s oceans. In 1969, computer scientists made proto-internet history when they linked four computers together at the same time. This sounds so simple, but it requires complex thinking: How do you decide which computer passes information in which direction, and how do you make sure everything arrives both quickly and safely?' },
		{ id: '7', title: 'Mark Zuckerberg was the 4th user to join Facebook', body: 'In Facebook profiles, each user is assigned a name based on when they joined. Mark Zuckerberg’s profile number ID is 4. The website was also originally called The Facebook.' },
		{ id: '8', title: 'The first YouTube video was uploaded in 2005', body: 'YouTube co-founder Jawed Karim uploaded the first video to YouTube in 2005. In the video, Karim walks around the San Diego Zoo.' },
		{ id: '9', title: 'Twitter was originally called Twttr', body: 'Twitter founder Jack Dorsey also sent the first tweet on March 21, 2006. It’s hard to imagine in the politically fraught, 280-character Twitter climate of 2020, but the site—originally called Twttr—was a microblogging service full of people sharing just a few words in a more diary-like style. Everything else, from active links to multimedia, came later.' },
		{ id: '10', title: 'The first Bitcoin transaction happened in 2009', body: 'In 2009, users made the first-ever transaction with cryptocurrency Bitcoin. Bitcoin combined the idea of a shadow economy with a then-new cryptography style called blockchain, with prices peaking at astronomical highs in the early 2010s.' },
		{ id: '11', title: '2.5 million people had a paid subscription to AOL in 2013', body: 'In 2013, more than 2.5 million people still paid to subscribe to AOL services. Statistically, these customers are likely to be in places that are underserved by broadband and still rely on vanishing dial-up services.' },
		{ id: '12', title: 'The 2016 "Baby Shark Dance" video holds the record for most YouTube views', body: 'The 2016 YouTube video for “Baby Shark Dance” holds the record for most YouTube views at over 8 billion, passing other multibillion club juggernauts like “Gangnam Style.” Slate’s podcast Decoder Ring explains that “Baby Shark” isn’t even a new song, but rather a children’s version of a song that dates back decades and has been performed by different artists.' },
		{ id: '13', title: '100% of emerging adults in the US are online', body: 'Pew Research reports that 100% of Americans age 18–29 use the internet. For adults overall, the number falls to a still astonishingly high 90%.' },
		{ id: '14', title: 'The first webpage is still online', body: 'Buzzfeed reports that the first website, a landing page at CERN’s domain describing what the “internet project” was trying to do, is still online after 29 years. CERN is where World Wide Web inventor Tim Berners-Lee put the global network online.' },
		{ id: '15', title: 'Internet Explorer turned 25 in 2020', body: 'Microsoft developed Internet Explorer to go out with its brand new Windows 95 operating system, and the iconic animated lowercase “e” icon followed internet users for the next 20 years until the release of Microsoft Edge in 2015.' },
		{ id: '16', title: 'AOL used half of all CD-ROM discs in the 1990s', body: 'During their peak in the mid-to-late 1990s, America Online (AOL) was using up 50% of all the CD-ROM discs in the world for their free software mailings. These usually came with offers of a certain number of free hours. The caveat was that many users didn’t have a local telephone number to dial, meaning they paid long-distance rates.' }
	]
}
